CONVERSION_DROP_THRESHOLD = 5          
FAILURE_SPIKE_THRESHOLD = 10           
SLA_HOURS_THRESHOLD = 4                

CONVERSION_DROP = "CONVERSION_DROP"
FAILURE_SPIKE = "FAILURE_SPIKE"
SLA_BREACH = "SLA_BREACH"

SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_HIGH = "HIGH"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_LOW = "LOW"

PRIORITY_CRITICAL = 100
PRIORITY_HIGH = 70
PRIORITY_MEDIUM = 40
PRIORITY_LOW = 10

ALERT_CONVERSION_THRESHOLD = 40        
ALERT_FAILURE_THRESHOLD = 50           
ALERT_SLA_BREACH_THRESHOLD = 100       